### ISSUE TITLE
Character models are not unique

### ISSUE THREAD

**Issue by moofrog** [Aizher800/CRE311-RoyalChairBrawl#14]
**Describe the bug**
In this build release, playtesters noted that the character models were not unique. The three characters present in the _Arena_ scene were all capsules and clones of each other.

**Version**
RoyalChairBrawl_alpha_v002

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the build found in the latest release [here](https://github.com/Aizher800/CRE311-RoyalChairBrawl/releases/tag/RoyalChairBrawl_alpha_v002). It is labelled 'New Unity Project' inside the RoyalChairBrawl_002 zip folder.
2. Once the _Main Menu_ appears click the `Start Game` button and wait for the _Arena_ scene to load.
3. See behaviour.

**Expected behaviour**
As per Royal Chair Brawl's [Dos and Don'ts](https://github.com/Aizher800/CRE311-RoyalChairBrawl/wiki/Dos-and-Don'ts), the character models are all unique in appearance and their abilities.

**Screenshots**
A screenshot of the capsule character models.
![Screenshot (380)](https://user-images.githubusercontent.com/60612224/82635379-9e847480-9c32-11ea-87f9-715936d23330.png)

**Desktop System:**
Unknown, presumably Windows.

**Additional context**
None.

**Comment by moofrog** [comment]
Replacements for the capsule character models have been brought into the scene. Each was replaced with _Char_Plaguedoc_v1_ and a weapon _Plague_Cane_ from the art repository. 


![Screenshot (397)](https://user-images.githubusercontent.com/60612224/83224701-a56e3280-a1b0-11ea-8082-415fb12115ed.png)


However, as can be seen below, the characters are still clones of each other. The model for the Monkey Ninja King is a work in progress. The goal is to have it brought into the scene to create some more diversity between players. After that is done, this enhancement will be fully completed.


![Screenshot (396)](https://user-images.githubusercontent.com/60612224/83224705-a606c900-a1b0-11ea-9b08-49eb73290df1.png)

**Comment by Aizher800** [comment]
The model of Monkey Ninja King is completed and have been brought into the scene. One of the Plague Doctor models in the scene has been replaced into the Monkey Ninja King model (_char_monkeyking_v2_ from the art repository). 

![image](https://user-images.githubusercontent.com/54401983/83858310-e2a56800-a74e-11ea-9f73-64f9890d513c.png)
