### ISSUE TITLE
Strength tag misinterpreted

### ISSUE THREAD

**Issue by moofrog** [Aizher800/CRE311-RoyalChairBrawl#15]
**Describe the bug**
40% of participants that playtested the build, misinterpreted the strength power-up tag. While most accurately understood what it represented, some believed the power-up to be for extra lives, or simply didn't know.

**Version**
RoyalChairBrawl_alpha_v002

**To Reproduce**
Steps to see the tag represented on the HUD:
1. Launch the build found in the latest release [here](https://github.com/Aizher800/CRE311-RoyalChairBrawl/releases/tag/RoyalChairBrawl_alpha_v002). It is labelled 'New Unity Project' inside the RoyalChairBrawl_002 zip folder.
2. Once the _Main Menu_ appears click the `Start Game` button and wait for the _Arena_ scene to load.
3. See the tags in the bottom right corner of the HUD display.

**Expected behaviour**
All players will be able to interpret the power-up tags as intended by the developers. 

**Screenshots**
None.

**Desktop System:**
Unknown, presumably Windows.

**Additional context**
None.

**Comment by Hamish-bytesize** [comment]
**Update**
Updated the Strength tag from muscular guy, to muscular arm.

*Original*
![Strength Boost tag](https://user-images.githubusercontent.com/64783346/83231834-bc1b8600-a1be-11ea-837b-40cf47c99564.png)
*Updated*
![Strength Boost tag 2](https://user-images.githubusercontent.com/64783346/83231905-d8b7be00-a1be-11ea-9cb6-ea60a4d6b3b1.png)

**Comment by ItsjustAvy** [comment]
![test of tags 1](https://user-images.githubusercontent.com/36540396/83724977-be288d80-a673-11ea-9fea-13f5e3784749.png)
reviewed update

I added the update to unity

**Comment by ItsjustAvy** [comment]
![test of tags 2](https://user-images.githubusercontent.com/36540396/83725058-e0baa680-a673-11ea-9860-cfd2b304dbf7.png)
explored another look for the power ups

**Comment by ItsjustAvy** [comment]
new tag looks good 
imported it into unity and the art repo
this a mock-up of an alt look for the tag (maybe it will work better for players to identify the power up/it might look better than a red/blue/green colored jug), this will be something you guys can decide on later I guess?
