### ISSUE TITLE
UI: Main Menu buttons incorrectly linked

### ISSUE THREAD

**Issue by moofrog** [Aizher800/CRE311-RoyalChairBrawl#6]
**Describe the bug**
During playtesting it was found that 50% of players found it difficult to navigate the UI. When player's launched the game and clicked the `Settings` button, it led them to a blank screen. They had to quit the game window and relaunch it to get back to the _Main Menu_. The `Tutorial` button was also bugged, as it led to the _Settings_ menu when clicked.

**Version**
RoyalChairBrawl_alpha_v002

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the build found in the latest release [here](https://github.com/Aizher800/CRE311-RoyalChairBrawl/releases/tag/RoyalChairBrawl_alpha_v002). It is labelled 'New Unity Project' inside the RoyalChairBrawl_002 zip folder.
2. Once the Main Menu appears click the `Tutorial` button.
3. See the error.
6. Quit and relaunch the game build.
7. Once the Main Menu appears click the `Settings` button.
8. See error.

**Expected behaviour**
On the _Main Menu_;
-  the `Tutorial` button should lead to the _Tutorial_ scene.
-  the `Settings` button should lead to the _Settings_ scene.

**Screenshots**
The scene that appears after clicking the `Settings` button on _Main Menu_.
![Screenshot (379)](https://user-images.githubusercontent.com/60612224/82593186-a6adc700-9bd4-11ea-9bcd-2de3123d0414.png)

**Desktop System (please complete the following information):**
Unknown, presumably Windows.

**Additional context**
None.

**Comment by moofrog** [comment]
I resolved this bug by removing the unnecessary scenes in _build settings_ and editing the _Ui_MainManager.cs_ script to accurately reference the new scene arrangement.

To replicate the steps I took:
1. Open our project in Unity.
2. Click File>Build Settings...
3. Under Scenes In Build, right-click any scene that doesn't belong and `Remove Selection`. I removed _Scenes/Ui_Pause_ and _Level design test_. 
This is what should remain:
![Screenshot (388)](https://user-images.githubusercontent.com/60612224/82734211-f367de00-9d4b-11ea-9502-aac378defaf2.png)
4. Ensure they numbered in the correct order (see the screenshot above for the correct arrangement).
5. Open _Erin_UI_MainManager.cs_ via the project window.
6.  Following the commented descriptions for each `public void`, change the `SceneManager.LoadScene(x);` number (represented by x) to the correct scene. It should look like this:
![InkedScreenshot (389)_LI](https://user-images.githubusercontent.com/60612224/82734502-f6fc6480-9d4d-11ea-947d-c58ac71445e0.jpg)
7. Save the script and open the _Ui_Menu_ scene.
8. Press play and click the menu links to see no errors.

**Comment by ItsjustAvy** [comment]
Clicking the tutorial button from the start menu takes me to this
![tutorial](https://user-images.githubusercontent.com/36540396/83857842-251a7500-a74e-11ea-9515-0fbed7bef08f.png)
From there I can press esc, then "restart" to get back to the main menu
(maybe the restart button should be renamed?, the quit button seems to do nothing)

Clicking settings in the main menu takes me to this 
![settings menu](https://user-images.githubusercontent.com/36540396/83857980-5c892180-a74e-11ea-9982-0e5291519b85.png)
the "back to main menu" button works
