### ISSUE TITLE
UI: Settings buttons incorrectly linked

### ISSUE THREAD

**Issue by moofrog** [Aizher800/CRE311-RoyalChairBrawl#7]
**Describe the bug**
During playtesting it was found that 50% of players found it difficult to navigate the UI. Along with the errors found in the [Main Menu bug](https://github.com/Aizher800/CRE311-RoyalChairBrawl/issues/6), there was an error found with the _Settings_ menu. When the `Back to Main Menu` button was clicked, it leads to a blank screen. Players had to quit and restart their game to navigate back to the _Main Menu_.

**Version**
RoyalChairBrawl_alpha_v002

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the build found in the latest release [here](https://github.com/Aizher800/CRE311-RoyalChairBrawl/releases/tag/RoyalChairBrawl_alpha_v002). It is labelled 'New Unity Project' inside the RoyalChairBrawl_002 zip folder.
2. Once the _Main Menu_ appears click the `Tutorial` button. (An error occurs here as it loads in the wrong scene, but it is addressed in another bug report [here](https://github.com/Aizher800/CRE311-RoyalChairBrawl/issues/6))
3. Once the _Settings_ menu has loaded, click the `Back to Main Menu` button.
8. See error.

**Expected behaviour**
On the _Settings_ menu;
-  the `Back to Main menu` button should lead to the Main Menu scene.

**Screenshots**
The blank scene that appears after clicking `Back to Main Menu` on the _Settings_ scene.
![Screenshot (377)](https://user-images.githubusercontent.com/60612224/82593304-e1affa80-9bd4-11ea-88ed-926e83d3fb11.png)
![Screenshot (378)](https://user-images.githubusercontent.com/60612224/82593346-f55b6100-9bd4-11ea-932c-1771271d5cfc.png)

**Desktop System (please complete the following information):**
Unknown, presumably Windows.

**Additional context**
None.

**Comment by moofrog** [comment]
This issue was resolved on fixing the [UI: Main Menu buttons incorrectly linked](https://github.com/Aizher800/CRE311-RoyalChairBrawl/issues/6) bug. The steps to reproduce are identical. The essential step involves adjusting the _Erin_UI_MainManager.cs_ script to the new scene arrangements. 

An essential step to this resolving bug:
Under `public void Return()` the scene number (represented by x) in `SceneManager.LoadScene(x); `should be set to the correct scene. This is what it should look like:
![InkedScreenshot (391)_LI](https://user-images.githubusercontent.com/60612224/82734986-faddb600-9d50-11ea-963e-3ccd3068e7a3.jpg)

**Comment by ItsjustAvy** [comment]
is the "back to main menu button" the quit button? 
the quit button seems not to work.

**Comment by ItsjustAvy** [comment]
I am able to get from the settings menu to the main menu
