### ISSUE TITLE
UI: Paused menu buttons incorrectly linked

### ISSUE THREAD

**Issue by moofrog** [Aizher800/CRE311-RoyalChairBrawl#8]
**Describe the bug**
During playtesting it was found that 50% of players found it difficult to navigate the UI. Once players had accessed the Pause menu while in the Arena scene, errors occurred when 
When player's launched the game and clicked the `Settings` button, it led them to a blank screen. They had to quit the game window and relaunch it to get back to the _Main Menu_. The `Tutorial` button was also bugged, as it led to the _Settings_ menu when clicked.

**Version**
RoyalChairBrawl_alpha_v002

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the build found in the latest release [here](https://github.com/Aizher800/CRE311-RoyalChairBrawl/releases/tag/RoyalChairBrawl_alpha_v002). It is labelled 'New Unity Project' inside the RoyalChairBrawl_002 zip folder.
2. Once the _Main Menu_ appears click the `Start Game` button.
3. After the scene loads press the ESC key.
4. Click `Restart Game`.
5. See error.

**Expected behaviour**
On the _Paused_ menu;
-  the `Restart Game` button should lead to the _Main Menu_ scene.

**Screenshots**
The blank screen that appears after clicking `Restart Game`.
![Screenshot (377)](https://user-images.githubusercontent.com/60612224/82593074-78c88280-9bd4-11ea-9323-bfb45228485f.png)

**Desktop System (please complete the following information):**
Unknown, presumably Windows.

**Additional context**
None.

**Comment by moofrog** [comment]
I resolved this bug by removing the unnecessary scenes in _build settings_ and editing the _Ui_PauseManager.cs_ script to accurately reference the new scene arrangement.

To replicate the steps I took:
1. Open our project in Unity.
2. Click File>Build Settings...
3. Under Scenes In Build, right-click any scene that doesn't belong and `Remove Selection`. I removed _Scenes/Ui_Pause_ and _Level design test_. 
This is what should remain:
![Screenshot (388)](https://user-images.githubusercontent.com/60612224/82734211-f367de00-9d4b-11ea-9502-aac378defaf2.png)
4. Ensure they numbered in the correct order (see the screenshot above for the correct arrangement).
5. Open _Erin_UI_PauseManager.cs_ via the project window.
6. For each `public void Restart()`, change the `SceneManager.LoadScene(x);` number (represented by x) to the correct scene. It should look like this:
![InkedScreenshot (390)_LI](https://user-images.githubusercontent.com/60612224/82735209-8dcb2000-9d52-11ea-91bf-74113091fb12.jpg)
7. Save the script and open the _Arena_ scene.
8. Press play then press ESC while in Unity's game window to bring up the pause menu overlay.
9. Click `Restart Game` to see no error.

**Comment by ItsjustAvy** [comment]
Review 
I have tried recreating the error
can confirm it has been solved
